[project]
name = "inventory-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crispy-tailwind>=1.0.3",
    "django>=5.2.8",
    "django-crispy-forms>=2.5",
    "faker>=38.2.0",
]
